Tue Jun 02 18:46:53 CEST 2020, Following exception was thrown: Specified itemID does not exist: 5
se.kth.iv1350.pos.integration.InvalidItemIDException: Specified itemID does not exist: 5
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:57)
	at se.kth.iv1350.pos.view.View.registerItem(View.java:61)
	at se.kth.iv1350.pos.view.View.sampleExecution(View.java:44)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:27)
Tue Jun 02 18:46:53 CEST 2020, Following exception was thrown: Could not connect to the database.
se.kth.iv1350.pos.integration.ItemCatalogException: Could not connect to the database.
	at se.kth.iv1350.pos.integration.ItemCatalog.fetchItem(ItemCatalog.java:59)
	at se.kth.iv1350.pos.controller.Controller.registerItem(Controller.java:53)
	at se.kth.iv1350.pos.view.View.registerItem(View.java:61)
	at se.kth.iv1350.pos.view.View.sampleExecution(View.java:45)
	at se.kth.iv1350.pos.startup.Main.main(Main.java:27)
